services:
  loki:
    image: grafana/loki:3.6.0
    container_name: loki
    restart: always
    user: "0:0"
    volumes:
      - /home/m1sk9/loki_data:/loki
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail:3.6.0
    container_name: promtail
    restart: always
    user: "0:0"
    volumes:
      - /var/log:/var/log:ro
      - /run/log/journal:/run/log/journal:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
